apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elastic
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=https://github.com/elastic/helm-charts/tree/main/elasticsearch}"